#+SETUPFILE: ~/repo/org-html-themes/setup/theme-readtheorg.setup

* Python

Repo containing python scripts and stuff.

** The Zen of Python

Beautiful is better than ugly.

Explicit is better than implicit.

Simple is better than complex.

Complex is better than complicated.

Flat is better than nested.

Sparse is better than dense.

Readability counts.

Special cases aren't special enough to break the rules.

Although practicality beats purity.

Errors should never pass silently.

Unless explicitly silenced.

In the face of ambiguity, refuse the temptation to guess.

There should be one-- and preferably only one --obvious way to do it.

Although that way may not be obvious at first unless you're Dutch.

Now is better than never.

Although never is often better than *right* now.

If the implementation is hard to explain, it's a bad idea.

If the implementation is easy to explain, it may be a good idea.

Namespaces are one honking great idea -- let's do more of those!


** Resources
- [[https://python.swaroopch.com/][A Byte of Python]]
- [[https://docs.python.org/3/tutorial/index.html][python.org]]
- [[https://amaral.northwestern.edu/resources/guides/pyenv-tutorial][Installing pyenv]]

** Tools

- [[https://github.com/proofit404/anaconda-mode][anaconda-mode]] :: Code navigation, documentation lookup and completion for Python.
- IPython ::  Pry for python
  pip install ipython

  #+BEGIN_SRC python
  from IPython import embed
  embed()
  #+END_SRC
- [[https://github.com/prompt-toolkit/ptpython][ptpython]] :: Nice REPL for python
#+BEGIN_SRC sh
pip install ptpython
#+END_SRC

- pyenv :: python version management tool. Equivalent of rbenv.

- [[https://github.com/proofit404/anaconda-mode][anaconda-mode]] :: Code navigation, documentation lookup and completion for Python.


** Data Structures

*** Lists

Pretty much like ruby's arrays.

#+BEGIN_SRC python :results output
list = ["a", "b", "c", "d"]

# accessing elements
list[0]

# adding elements
list.append("e")

#+END_SRC

Python is not as object-oriented as ruby, so you have to use function to work on lists.

#+NAME: list-of-numbers
#+BEGIN_SRC python
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
#+END_SRC

#+BEGIN_SRC python :results output :noweb yes
<<list-of-numbers>>
#             __________________ lambda expression!
even = filter(lambda x: x%2 == 0, numbers)
print(even)
#+END_SRC 

#+RESULTS:
: [2, 4, 6, 8, 10]

**** Methods
- append()	
- extend(iterable) :: appends items from an iterable.
  #+BEGIN_SRC python :results output :noweb yes
  <<list-of-numbers>>
  numbers.extend([11,12,13])
  print(numbers)
  #+END_SRC

  #+RESULTS:
  : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

- insert(x,y)
  #+BEGIN_SRC python :results output :noweb yes
    <<list-of-numbers>>
    index = 0
    value = 999
    numbers.insert(index, value)
    print(numbers)
  #+END_SRC

  #+RESULTS:
  : [999, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

- remove(value)
*Returns an error if there is no such item.*
  #+BEGIN_SRC python :results output :noweb yes
    <<list-of-numbers>>
    numbers.remove(5)
    numbers.remove(6)
    numbers.remove(7)
    print(numbers)
  #+END_SRC

  #+RESULTS:
  : [1, 2, 3, 4, 8, 9, 10]

- pop([value])
Removes item at the given position and returns it.
If no value is given, it returns the last element and removes it.
See note on optional parameters

  #+BEGIN_SRC python :results output :noweb yes
  #+END_SRC

** Lambdas

#+BEGIN_SRC python :results output
l = lambda var : var * var
print(l(5))
#+END_SRC

** Terms and language specific 

- <<<optional parameters>>> :: Brackets in method signatures denote that the value is in the bracket is optional.
- Iterator :: an object that can be iterated upon. EG lists, tuples, strings.
An iterator must implement the methods __iter__() and __next__()



** Data Structures and Algorithms in Python
*** Chapter 4 Recursion
#+BEGIN_SRC python :results output
def factorial(x):
    if x == 0:
        return 1
    else:
        return x * factorial(x - 1)

print(factorial(3))
#+END_SRC

#+RESULTS:
: 6





** Reloading module 
#+BEGIN_SRC python
    import importlib
    importlib.reload(module)
#+END_SRC
** Sample code

*** Shortest range in k sorted lists
Given k sorted lists of integers of size n each, find the smallest range that
includes at least one element from each of the k lists.
If more than one smallest ranges are found, print any one of them.
#+BEGIN_SRC python :results output
    list1 = [4, 10, 15, 24]
    list2 = [0,  9, 12, 20]
    list3 = [5, 18, 22, 30]

          for numbers in a:
              min 
#+END_SRC


*** Heap
#+BEGIN_SRC python :results output
  class MyHeap:
      def __init__(self, lst):
          self.heap = [0]
          self.heap = self.heap.append(lst)

      def heap:
          return heap;

      def left_index(self, index):
          return 2 * index

      def right_index(self, index):
          return 2*index + 1

      def parent_index(self, index):
          return (index/2) + 1

      def swap(self, index1, index2):
          temp = self.heap[index1]
          sh
#+END_SRC




** Q&A

Whats the difference between == and is?

==  evaluates value equality
`is`  

How do you print on the same line?
#+BEGIN_SRC python :results output
print("same", end ="") 
print(" line", end ="") 

#+END_SRC

#+RESULTS:
: same line

* Algorithms and Data Structures
** Recursion
- You must describe the task at hand in terms of itself
- Each function call must perform one task
  - Each function is a worker doing a *part* of the worker

- Every recursive algorithm involves at least 2 cases:
  - <<base case>> :: Simple occurrence that can be answered directly

  - <<recursive case>> ::  A complex occurrence that cannot be answered
       directly. Instead, it can be described in terms of smaller occurrences of
       the same problem.
  
  Usually, the [[base case]] is the case where the problem has been solved. 
  
  Key: Ask yourslef, How can I describe this algorithm in terms of a smaller or
  simpler version of itself?
 
*** Some points
- All the work usually starts at the end, so think what is the last thing i need to do ([[base case]])
- Trust that all the function call are doing their work.
- Where you call your function recursively matters.
  - Should you place it before or after your function performs their task?
- Can the base case be 'do nothing'? 
   IE return an empty array, empty string, etc.

*** Examples
**** Print the number of stars 
#+BEGIN_SRC python :results output :export both
  def print_stars(number_stars):
      if number_stars == 1: # base case
          print("*")
      else:
          print("*") # You can move both prints to the top of the function
          print_stars(number_stars - 1)

  print_stars(5)
#+END_SRC

#+RESULTS:
: *
: *
: *
: *
: *

**** Power
#+BEGIN_SRC python :results output :export both
  def power(base, exp): # you  had power(base, power) and the function sig was conflicting with the var
      if exp == 0:
          return 1
      else:
          return base * power(base, exp - 1)

  print(power(3, 0))
  print(power(3, 1))
  print(power(3, 3))
#+END_SRC

#+RESULTS:
: 1
: 3
: 27

**** Palindrome
#+BEGIN_SRC python :results output

  def is_palindrome(string):
      if len(string) <= 2:
          return True
      else:
          if string[0] == string[-1]:
              return is_palindrome(string[1:-1])
          else:
              return False

  print(is_palindrome('racecar'))
  print(is_palindrome('palindrome'))
  print(is_palindrome('oliilo'))
#+END_SRC

#+RESULTS:
: True
: False
: True


**** Print binary
#+BEGIN_SRC python :results output :export both
  def print_binary(number):
      if number < 2:
          print(1, end = '')
      else:
          last_digit = number % 2 # See note 1
          rest_of_digits = number // 2 # see note 2
          print_binary(rest_of_digits)
          print(str(last_digit),end = '') # this wont be reached until the very last digit because of the previous line
  print_binary(10)
#+END_SRC

#+RESULTS:
: 1010

- Note 1
  Just like when you want to pop a number in decimal.
  EG
  14 % 10 = 4

  # 11 in binary is 1011
  11  % 2 = 1
  or 1010

- Note 2
  The '//' operator is floor division. If you use regular division, you will get decimals.
  
**** Reverse array 
#+BEGIN_SRC python :results output :exports both
  def reverse_array(ar):
      print(ar)
      if len(ar) == 0:
          return []
      else:
          last = ar.pop()
          rev = reverse_array(ar)
          rev.insert(0, last)
          print(rev)
          return rev

  print(reverse_array([4, 3,2,1,0 ]))
#+END_SRC

#+RESULTS:
#+begin_example
[4, 3, 2, 1, 0]
[4, 3, 2, 1]
[4, 3, 2]
[4, 3]
[4]
[]
[4]
[3, 4]
[2, 3, 4]
[1, 2, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
#+end_example

** When optimizing and algorithm
Bottlenecks
Necessary work
Duplicate Work

** Data structures
*** Trees
**** Ordering

- inorder ::
- postorder ::
- preorder ::

*** Graphs

- graph ::
  A graph represents a relationship that exist between pairs of objects.
  These objects are called vertices.
  The object have a pairwise connection called edges.

  Graphs can be applied to mapping, transportation, computer networks,
  and electrical engineering.

  Graphs are not function plots, histograms, etc.

- directed graph :: a set of nodes that are unidirectional.

- undirected graph :: a set of nodes that are bidirectional.

- degree :: number of edges connecting to a vertex.

- indegree :: number of incoming edges connecting to a vertex.

- outdegree :: number of incoming edges connecting to a vertex.







** Questions
*** Find the middle of a linked list
We can:
First approach
  - traverse the list once
  - get size
  - traverse to half the length

 Space O(n)
 Space O(1)


A better approach:
  - You slow and fast pointer
    - slow goes at 1 speed 
    - fast goes at 2^n speed

      Time:  O(n/2)
      Space: O(1)

   Example.
#+BEGIN_SRC 
|------------+-----------------------|
| iternation | list                  |
|   starting | f                     |
|            | s                     |
|            | [0][1][2][3][4][5][6] |
|------------+-----------------------|
|          1 | -------f              |
|            | ----s                 |
|            | [0][1][2][3][4][5][6] |
|------------+-----------------------|
|          2 | -------------f        |
|            | -------s              |
|            | [0][1][2][3][4][5][6] |
|------------+-----------------------|
|          3 | -------------------f  |
|            | ----------s           |
|            | [0][1][2][3][4][5][6] |
|------------+-----------------------|

#+END_SRC

